language: python
sudo: false
python:
  - "3.3"
  - "2.7"

install: pip install -r requirements-test.txt

script:
- flake8
- coverage run --source zeropush runtests.py

# report coverage to coveralls.io
after_success: coveralls
